FROM node:latest
USER root

# Bundle APP files
COPY . .

# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install
RUN npm run build

# Expose the listening port of your app
EXPOSE 3000

CMD ["npm", "run", "start:prod"]
