version: "3.9"
services:
  postgres-keycloak:
    image: postgres:latest
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    command:
      - -p 5433
    expose:
      - "5433"
    ports:
      - "5433:5433"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres-keycloak
      - DB_DATABASE=keycloak
      - DB_PORT=5433
      - DB_SCHEMA=public
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - postgres-keycloak
    command:
      - start-dev

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "calendar_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/calendar_db -schemas=public -user=postgres -password=postgres migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - postgres
    restart: on-failure

#  app:
#    image: calendar_app_image
#    build:
#      context: .
#      dockerfile: ./DockerFile
#    ports:
#      - "3000:3000"
#    environment:
#      - PG_DATABASE=calendar_db
#      - PG_HOST=postgres
#      - PG_PORT=5432
#      - PG_USERNAME=postgres
#      - PG_PASSWORD=postgres
#
#      - KEYCLOAK_SERVER_URL=http://keycloak:8080
#      - KEYCLOAK_REALM=calendar-realm
#      - KEYCLOAK_CLIENT_ID=calendar-app
#      - KEYCLOAK_SECRET=
#    depends_on:
#      - postgres
#      - postgres-keycloak
